spring.application.name=CyberWebApp
# C?u h�nh k?t n?i MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cyberweb
spring.datasource.username=root
spring.datasource.password=qqqweasd12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true